### ISSUE TITLE
Application in Launcher shows "20009Scape"

### ISSUE THREAD

**Issue by 7MXek** [2009scape/2009Scape-mobile#11]
### Describe the bug

The application icon in my launcher shows "20009Scape". This is one too many zeros.

### The log file and images/videos

![screenshot_20009Scape](https://github.com/2009scape/2009Scape-mobile/assets/46906604/007cf949-4c80-496a-aeff-d1dbd4996c53)

### Steps To Reproduce

```markdown
Install the application and look at the name in the application launcher.
```

### Expected Behavior

Application name should be "2009Scape".

### Platform

```markdown
- Device model: Pixel 6a
- CPU architecture: aarch64
- Android version: 13
- 2009Scape-mobile version: Release 2.0
```

**Comment by 7MXek** [comment]
I've created a pull request with a change that I believe should fix this.

https://github.com/2009scape/2009Scape-mobile/pull/12

**Comment by downthecrop** [comment]
Lol how was this not noticed until now haha. I'll get this next update thank you.
