### ISSUE TITLE
[F-Req] Custom servers

### ISSUE THREAD

**Issue by minatsukiyo** [2009scape/2009Scape-mobile#13]
### Describe the request.

I've been looking into how to refer to the private 2009scape server that my friend is hosting for the mobile app.
And I can't seem to find instructions for it.

**Comment by downthecrop** [comment]
You can load a config in the settings. Need to scroll below the plugins
![Screenshot_20231012-185147_2009Scape](https://github.com/2009scape/2009Scape-mobile/assets/4764745/7859c521-2cc0-4643-a02e-a6e3a83e12fa)
